#!/bin/bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DIR

usage() {
    echo "Usage: ${0##*/}"
    exit 1
}

if [[ "$#" -gt 0 ]]; then
  usage
fi

if ! command -v git > /dev/null; then
  echo "git is missing."
  exit 1
fi

GIT_COMMIT=$(git rev-list -1 HEAD)

mkdir -p ${DIR}

echo "{\"gitCommit\": \"${GIT_COMMIT}\"}" > "${DIR}/../build/health.json"
